# Generated by Django 3.1.7 on 2021-03-06 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinput',
            old_name='blood_pressure',
            new_name='blood_pressure_high',
        ),
        migrations.AddField(
            model_name='userinput',
            name='blood_pressure_low',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
    ]
