# Generated by Django 3.1.7 on 2021-03-06 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0002_auto_20210306_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinput',
            old_name='blood_pressure_high',
            new_name='high_blood_pressure',
        ),
        migrations.RenameField(
            model_name='userinput',
            old_name='blood_pressure_low',
            new_name='low_blood_pressure_low',
        ),
    ]
